# Numpy

* Numpy is general-purpose array-processing library.
* It provided a high-performance multi-dimentional array object, and tools for working with arrays.
* It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.
* Numpy array is a collection of homogeneous elements.
* For more information refer - https://numpy.org/doc/stable/user/absolute_beginners.html

In [1]:
# Importing 

import numpy as np

In [2]:
# Creating a list

l = [2, 4, 6, 8, 10]

# Converting list to numpy array
arr = np.array(l)

print(type(arr))
arr # 1-D array

<class 'numpy.ndarray'>


array([ 2,  4,  6,  8, 10])

In [3]:
# Shape (Gives number of rows and columns)

arr.shape

(5,)

In [4]:
# Multi-Dimensionl array

l1 = [1, 2, 3, 4]
l2 = [4, 5, 6, 7]
l3 = [7, 8, 9, 10]

arr1 = np.array([l1, l2, l3])
arr1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [5]:
arr1.shape

(3, 4)

In [6]:
# How do I change the dimensions of an array?
# Make sure the rows*columns match with the total number of elements while using reshape

arr1.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [7]:
arr1.reshape(5, 4) # ValueError: cannot reshape array of size 12 into shape (5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

### Indexing 

In [8]:
# Creating a 1-D array

arr2 = np.array([1, 2, 3, 4, 5])

# Accessing elements of array
arr2[2]

3

In [9]:
# Creating a 2-D array

arr3 = np.array([[1, 2, 3], [2, 4, 6], [2, 5, 7]])

# Accessing elements of array 
arr3[0][2]

3

In [10]:
# Slicing through array

arr3[:, :]

array([[1, 2, 3],
       [2, 4, 6],
       [2, 5, 7]])

In [11]:
arr3[0:2, 0:2] # First two rows, first two elements

array([[1, 2],
       [2, 4]])

In [12]:
arr3[:3, :1]

array([[1],
       [2],
       [2]])

In [13]:
arr4 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [9, 7, 6, 8, 9]])

arr4

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
arr4[1, 2:4], arr4[2, 3:5] # Accessing 4,5 from 1st row and 6,8 from second row (Using o based indexing)

(array([4, 5]), array([8, 9]))

### In-Built Functions

In [15]:
# arange - Creates a 1-D array
# Syntax - np.arange(start, stop, step)

arr5 = np.arange(0, 5)
arr5

array([0, 1, 2, 3, 4])

In [16]:
arr6 = np.arange(0, 10, 2)
arr6

array([0, 2, 4, 6, 8])

In [17]:
# linspace - Creates equally spaced points 
# Syntax - np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

arr7 = np.linspace(0, 5, num=10)
arr7

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
# broadcasting - replacing array elements by some value

arr8 = np.array([1, 2, 3, 4, 5])
arr8[3:] = 100 # Replacing 4, 5 with 100
arr8

array([  1,   2,   3, 100, 100])

In [19]:
arr9 = np.array([1, 2, 3, 4, 5])
arr9[3:] = 500
arr9

array([  1,   2,   3, 500, 500])

In [20]:
# copy - creates a copy of an array (creating another memory space)

arr9 = arr8.copy()
arr9[3:] = 1000
arr9

array([   1,    2,    3, 1000, 1000])

In [21]:
arr8

array([  1,   2,   3, 100, 100])

In [22]:
# Creating a variable and an array

x = 5
arr10 = np.array([2, 4, 5, 8, 10])

arr10 > 5 # Simillary can perform math operations such as *, /, %

array([False, False, False,  True,  True])

In [23]:
arr10[arr10 < 5] # Returns elements which are less than 5

array([2, 4])

In [24]:
# Multiplication of arrays

arr11 = np.array([1, 2, 3])
arr12 = np.array([2, 4, 6])

arr11 * arr12

array([ 2,  8, 18])

**Important - For multiplication in case of multi-dimentional arrays, the number of columns of first n-D array should be equal to number of rows of second n-D array**

In [25]:
# ones - Creates an array with 1's as all elements 
# Syntax - np.ones(shape, dtype)

arr13 = np.ones((2, 2), dtype=int)
arr13

array([[1, 1],
       [1, 1]])

In [26]:
# zeros - Creates an array with 0's as all elements 
# Syntax - np.zeros(shape dtype)

arr14 = np.zeros((2, 2), dtype=int)
arr14

array([[0, 0],
       [0, 0]])

In [27]:
# rand() - Creates a random distribution b/w 0 to 1 using uniform distribution
# Syntax - np.random.rand(shape)

arr15 = np.random.rand(2, 2)
arr15

array([[0.20894615, 0.34688016],
       [0.66785405, 0.54748171]])

In [28]:
# randn - Creates a random distribution using standard normal distribution
# Syntax - np.random.randn(shape)

arr16 = np.random.randn(2, 2)
arr16

array([[0.28852836, 1.89130205],
       [0.51318914, 0.00301902]])

In [29]:
# randint - Creates a array with random elements 
# Syntax - np.random.randit(low, high, size, dtype)

arr17 = np.random.randint(low=0, high=10, size=5, dtype=int)
arr17

array([9, 8, 8, 7, 8])

In [30]:
# random_sample - Creates random floats in half open interval [0.0, 1.0) based on continuous distribution
# Syntax - np.random.random_sample(size)

arr18 = np.random.random_sample(size=(2, 5))
arr18

array([[0.54947867, 0.13459234, 0.8359969 , 0.01657223, 0.41572191],
       [0.00753354, 0.78346958, 0.83337064, 0.08977834, 0.22231578]])